### ISSUE TITLE
Add Nextcloud as fileservice

### ISSUE THREAD

**Issue by mathiasbosman** [mathiasbosman/file-services#14]
**Nextcloud** offers a Java sdk to integrate with their services.

Things to analyze:

- [x] is it actively maintained
- [x] can we implement existing features
- [x] can we run it in a container for test purposes
- [x] how is security handled (possible OAuth?)

**Comment by mathiasbosman** [comment]
We can run it in docker with this docker compose file:
```
version: '2'

services:
  nextcloud-db:
    image: mariadb
    restart: always
    command: --innodb-read-only-compressed=OFF
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 9001:80
    links:
      - nextcloud-db
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
```
