### ISSUE TITLE
Nextcloud tests are slow

### ISSUE THREAD

**Issue by mathiasbosman** [mathiasbosman/file-services#25]
See if we can impove the speed of the Nextlcoud tests by chanching the underlying database to MySQL

**Comment by mathiasbosman** [comment]
The SQL db seems to ignore the `NEXTCLOUD_ADMIN_USER` en `NEXTCLOUD_ADMIN_PASSWORD` env variables used by the Docker compose file..

**Comment by mathiasbosman** [comment]
Changing to MySQL DB (MariaDB) doesn't really give a lot of speed improvements.
As Nextcloud is mostly used with PostgreSQL databases we'll just keep it as it is.

**Comment by mathiasbosman** [comment]
For future reference, this is the docker-compose file used

```yaml
services:
  fs-test-nextcloud-db:
    image: mariadb
    restart: always
    ports:
      - 9001:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  fs-test-nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 9002:80
    links:
      - fs-test-nextcloud-db
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=fs-test-nextcloud-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
```
